### ISSUE TITLE
Negative margin shifts content

### ISSUE THREAD

**Issue by Spielboerg** [jasmine/jasmine#1788]
The element with the CSS class `jasmine_html-reporter` has a margin of `-8px`. This results in the compiled components being pushed up into the gray box and the gray box is not 100% wide and leaves a small gap on the right side:

![Karma](https://user-images.githubusercontent.com/7893762/74742601-2b4c1a80-525f-11ea-85d4-9006505d4dfd.jpg)

## Expected Behavior
Page layout is correct and no elements overlap each other.

## Current Behavior
Tested components overlap with gray box + white gap on the right side.

## Possible Solution
Add following rules:
```css
body {
  margin: 0;
}

.jasmine_html-reporter {
  box-sizing: border-box;
  // margin: -8px;        // removing this line from the current CSS
}
```

## Your Environment
* Version used: 4.4.1
* Environment name and version: Chrome 79
* Operating System and version (desktop or mobile): macOS 10.15.3
